version: '3'

services:
  next:
    build: ./next
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./next:/app
    depends_on:
      - postgres
  api:
    build: ./api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres
  # nginx:
  #   # image: nginx:latest
  #   # ports:
  #   #   - '80:80'
  #   # volumes:
  #   #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   #   - ./next/.next:/usr/share/nginx/html
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - api
  #     - next
  #   ports:
  #     - '80:80'
    # environment:
    #   - NEXTJS_CONTAINER_IP=nextjs-app # supplying environment vars for convert-nginx.sh file.
    # command: ['sh', '/etc/nginx/convert-nginx.sh'] # - пример https://github.com/csrinu236/medium-nextjs-nginx-setup/blob/simple-nginx/docker-compose.yml
  postgres:
    image: postgres
    restart: always
    ports: 
      - '5433:5432'
    volumes:
      - ./CD-DataBase.sql:/docker-entrypoint-initdb.d/CD-DataBase.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: codedirectory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23400
volumes:
  postgres_data: