version: '3'

services:
  next:
    build: ./next
    restart: always
    ports:
      - '3000:3000'
    # volumes:
    #   - ./next:/app
    depends_on:
      - postgres
  api:
    build: ./api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    depends_on:
      - api
      - next
    ports:
      - '80:80'
    environment:
      - NEXTJS_CONTAINER_IP=next # supplying environment vars
  postgres:
    image: postgres
    restart: always
    ports: 
      - '5433:5432'
    volumes:
      - ./CD-DataBase.sql:/docker-entrypoint-initdb.d/CD-DataBase.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: codedirectory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23400
volumes:
  postgres_data: