import './components/styles/globals.css';
import { Montserrat } from 'next/font/google';
import Header from '@/app/components/headernav/headernav.jsx';
import Footer from '@/app/components/footer/footer.jsx';

import { AppStateProvider } from './context.jsx';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' })

export const metadata = {
  title: 'CodeDirectory',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AppStateProvider>
        <html lang="en" className={montserrat.variable}>
            <body>
            <Header/>
                <main className='flexGrow'>
                    {children}
                </main>
            <Footer/>  
            </body>
        </html>
    </AppStateProvider>
    )
}
